Release 1.1
hyperlinkgroup/uikit-components pull request #3
Opened 2023-01-20 09:38 UTC by annanna

- Added reusable Components from AppState.dev and Plantbuddy
- Added BaseButton-Class from AppState-Package
- Changed Content Mode of BaseImageView

2023-01-24 07:02 UTC, kaevinio requested changes
Die Doku ist fast überall noch auf Deutsch

2023-01-24 07:02 UTC, kaevinio commented on Sources/UIKitComponents/Extensions/CellIdentifier.swift
> +public extension UICollectionViewCell {
Warum ist hier überall die Einrückung weg?

2023-01-24 07:02 UTC, kaevinio commented on Sources/UIKitComponents/Extensions/NSFetchedResultsController.swift
> +/**
Kommentar lieber in Englisch oder?

2023-01-24 07:02 UTC, kaevinio commented on Sources/UIKitComponents/Extensions/String.swift
> +    /**
Auch hier der Kommentar

2023-01-24 07:02 UTC, kaevinio commented on Sources/UIKitComponents/Extensions/String.swift
> +    /**
Also ist jetzt fraglich mit dieser Funktions. Klar wir bieten das als Package und wir benutzen das auch noch manchmal, aber eigtl. sollte das nicht mehr genommen werden. Wir haben auf Compositional umgestellt und StackViews, da wird die Höhe automatisch festgelegt, ohne wie hier eine feste Größe zu berechnen

2023-01-24 07:02 UTC, kaevinio commented on Sources/UIKitComponents/Extensions/UICollectionView.swift
> +/**
Sprache

2023-01-24 07:02 UTC, kaevinio commented on Sources/UIKitComponents/Extensions/UICollectionView.swift
> +      indexPath.section < numberOfSections && indexPath.row < numberOfItems(inSection: indexPath.section)
Okay also die Funktion heißt gleich wie bei CoreData aber checkt das anders. Bin grad nicht mehr tief genug drin, ob das so Sinn ergibt, dass die Funktionen unterschiedlich sind, wenn ja beides auf einen existierenden IndexPath checkt.

2023-01-24 07:02 UTC, kaevinio commented on Sources/UIKitComponents/Extensions/UIColor.swift
> +        return  cgColor.numberOfComponents == 2 ? ColorComponents(r:components[0], g:components[0], b:components[0], a:components[1]) : ColorComponents(r:components[0], g:components[1], b:components[
nach dem return ist ein Leerzeichen zu viel

2023-01-24 07:02 UTC, kaevinio commented on Sources/UIKitComponents/Extensions/UIColor.swift
> +extension UIColor {
Warum ist das hier bei den Components? Das wäre ja eher für die Utilities oder? Also ja könnte man drüber diskutieren, wo es besser passt

2023-01-24 07:02 UTC, kaevinio commented on Sources/UIKitComponents/Extensions/UIImage.swift
> +public extension UIImage {
Ich finde iwie auch die Funktionen passen nicht wirklich zu den Components, weil das sind ja Sachen für Bilder. Aber jetzt components in iwas generischeres umzubenennen ist bestimmt auch doof, also sehen wir es dann eher als Sammlung für UIKit stuff

2023-01-24 07:02 UTC, kaevinio commented on Sources/UIKitComponents/Extensions/UIImage.swift
> +     Anpassung der Orientierung eines Bildes.
Aber die Doku trotzdem auf Englisch

2023-01-24 07:02 UTC, kaevinio commented on Sources/UIKitComponents/Extensions/UIScreen.swift
> +    /**
Doku

2023-01-24 07:02 UTC, kaevinio commented on Sources/UIKitComponents/Extensions/UIScrollView.swift
> +     Zum Ende eines ScrollViews scrollen.
Doku

2023-01-24 07:02 UTC, kaevinio commented on Sources/UIKitComponents/Extensions/UIView.swift
> +     Hinzufügen eines Farbverlaufs.
Also ich glaube leider, das funktioniert nicht so easy, wie es hier ist. Ich hattte immer wieder Probleme, bei UIKit einen Gradient zu machen und wir benutzen das glaube auf komische Art und Weise. Also entweder noch mehr Doku dazu oder ch würds eher rausnehmen und nur bei Plantbuddy da drin lassen, wo es funktioniert

2023-01-24 07:02 UTC, kaevinio commented on Sources/UIKitComponents/Views/Buttons/BaseButton.swift
> +open class BaseButton: UIButton {
Hmm da steht ja, dass ich das erstellt habe, aber iwie finde ich es mittlerweile komisch, wenn das nur BaseButton heißt, wenn man optional nur ein Bild reingeben kann und keinen Text. Dann lieber BaseImageButton?

2023-01-24 07:02 UTC, kaevinio commented on Sources/UIKitComponents/Views/Cells/BaseCollectionViewCell.swift
> +            guard let color = selectionColor else { return }
hier können wir guard let selectionColor

2023-03-03 09:59 UTC, annanna commented on Sources/UIKitComponents/Extensions/CellIdentifier.swift
> +public extension UICollectionViewCell {
das `public` gilt jetzt für die ganze Extension, dann muss man es nicht an jede einzelne Funktion/Property schreiben

2023-03-03 10:00 UTC, annanna commented on Sources/UIKitComponents/Extensions/String.swift
> +    /**
wird in PB auf jeden Fall an sehr vielen Stellen genutzt. Willst du es aus dem Package raus haben und einzeln in PB rein?

2023-03-03 10:21 UTC, annanna commented on Sources/UIKitComponents/Extensions/UIImage.swift
> +public extension UIImage {
Ich versteh nicht ganz was du meinst. Also ja, für mich ist es ne UIKit-Sammlung hier. Was ist es denn für dich?

2023-03-03 10:28 UTC, annanna commented on Sources/UIKitComponents/Extensions/UICollectionView.swift
> +      indexPath.section < numberOfSections && indexPath.row < numberOfItems(inSection: indexPath.section)
NSFetchedResultsController hat nicht die gleichen Funktionen/Properties, können die nicht analog benutzen

2023-03-03 10:32 UTC, annanna commented on Sources/UIKitComponents/Views/Buttons/BaseButton.swift
> +open class BaseButton: UIButton {
hab es komplett rausgenommen, es war ja das gleiche wie `BaseButtonWithImage`

2023-03-06 06:27 UTC, kaevinio commented on Sources/UIKitComponents/Extensions/String.swift
> +    /**
Also da es veraltet ist würde ich es im Package lieber nicht mehr anbieten

2023-03-06 06:28 UTC, kaevinio commented on Sources/UIKitComponents/Extensions/String.swift
> +    /**
Wobei theoretisch kann man es auch drin lassen, falls jemand das Package nutzt kann er die Funktion nutzen, also lass es so.

2023-03-06 06:29 UTC, kaevinio approved these changes

2023-03-06 08:31 UTC, merged